> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function =np.concatenate
- function =np.transpose
- function =np.vstack
- function =np.hsplit
- function np.linalg

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [3]:
!pip install jovian --upgrade -q

In [4]:
import jovian

In [5]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

In [44]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.Traspose
function3 = np.splitting & vstack & hstack
function4 = np.Datetime64
function5 = np.linalg

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [10]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [9]:
# Example 2 - working
arr3=[[1,2],
     [3,4]]

arr4=[[11,12],
     [14,15]]
np.concatenate((arr3,arr4))

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [14, 15]])

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Some closing comments about when to use this function.

In [27]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Function 2 - Transpose

Add some explanations

In [12]:
# Example 1 - working

# transpose
arr1

[[1, 2], [3, 4.0]]

In [13]:
t1=np.transpose(arr1)
t1

array([[1., 3.],
       [2., 4.]])

Explanation about example

In [14]:
# Example 2 - working
arr2

[[5, 6, 7], [8, 9, 10]]

In [15]:
t2=np.transpose(arr2)
t2

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
np.concatenate((t1,t2),axis=0)

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 5.,  8.],
       [ 6.,  9.],
       [ 7., 10.]])

Some closing comments about when to use this function.

In [28]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Function 3 - splitting     hsplit and vslipt

Add some explanations

In [18]:
# Example 1 - working
# splitting

a=np.array([[1,2,3,4,5,6],
           [8,9,10,11,12,13]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13]])

In [19]:
# horizontal split

h=np.hsplit(a,2)
h

[array([[ 1,  2,  3],
        [ 8,  9, 10]]),
 array([[ 4,  5,  6],
        [11, 12, 13]])]

Explanation about example

In [20]:
# Example 2 - working
a1=np.array([[14,15,16,17,18,19,20,21],
            [22,23,24,25,26,27,28,29]])
a1

array([[14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
v=np.vsplit(a1,2)
v

[array([[14, 15, 16, 17, 18, 19, 20, 21]]),
 array([[22, 23, 24, 25, 26, 27, 28, 29]])]

Some closing comments about when to use this function.

In [29]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Function 3 -  vstack and hstack

Add some explanations

In [25]:
# Example 1 - vstack

a1=np.array([[12,13,14],
           [51,61,71]])

a=np.array([[15,16,17],
          [18,19,20]])

v=np.vstack((a1,a))
v

array([[12, 13, 14],
       [51, 61, 71],
       [15, 16, 17],
       [18, 19, 20]])

Explanation about example

In [26]:
# Example 2 - hstack

v1=np.hstack((a1,a))
v1

array([[12, 13, 14, 15, 16, 17],
       [51, 61, 71, 18, 19, 20]])

Some closing comments about when to use this function.

In [30]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Function 4 - datetime64

Add some explanations

In [33]:
# Example 1 - working

today=np.datetime64('2021-02-26')
print("date is:",today)
print("year is:",np.datetime64(today,'Y'))

date is: 2021-02-26
year is: 2021


Explanation about example

In [34]:
# Example 2 - increment

dates=np.arange('2021-02','2021-03',dtype='datetime64[D]')

print("\nDates of feb,2021:\n",dates)
print("Today is feb:",today in dates)


Dates of feb,2021:
 ['2021-02-01' '2021-02-02' '2021-02-03' '2021-02-04' '2021-02-05'
 '2021-02-06' '2021-02-07' '2021-02-08' '2021-02-09' '2021-02-10'
 '2021-02-11' '2021-02-12' '2021-02-13' '2021-02-14' '2021-02-15'
 '2021-02-16' '2021-02-17' '2021-02-18' '2021-02-19' '2021-02-20'
 '2021-02-21' '2021-02-22' '2021-02-23' '2021-02-24' '2021-02-25'
 '2021-02-26' '2021-02-27' '2021-02-28']
Today is feb: True


Some closing comments about when to use this function.

In [35]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Function 5 - np.linalg.matrix_rank

Add some explanations

In [39]:
# Example 1 - index

a=np.array([[1,2,3],
           [4,-5,6],
          [2,8,7]])

print("Rank of a",np.linalg.matrix_rank(a))

Rank of a 3


In [40]:
print("\nInverse of a:\n",np.linalg.inv(a))


Inverse of a:
 [[-7.54545455  0.90909091  2.45454545]
 [-1.45454545  0.09090909  0.54545455]
 [ 3.81818182 -0.36363636 -1.18181818]]


In [41]:
# Example 2 - working
print("\nMatrix a raised to power 3:\n",np.linalg.matrix_power(a,3))


Matrix a raised to power 3:
 [[ 151  238  393]
 [ 368 -221  642]
 [ 334  820  985]]


In [42]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations


'https://jovian.ai/nikgopale4/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()