


# Numpy Functions


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.reshape       
function2 = np.setdiff1d     
function3 = np.intersect1d   
function4 = np.where         
function5 = np.argmax        


The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [3]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [4]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "nikgopale4/numpy-array-operations-assigment-2"
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2


'https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [13]:
# List of functions explained 
function1 = np.reshape       
function2 = np.setdiff1d     
function3 = np.intersect1d   
function4 = np.where         
function5 = np.argmax        

## Function 1 - np.reshape

To reshape a matrix provided new shape should be compatible with the original shape

In [6]:
# Example 1 - shapes an array without changing data of array.
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

a.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Reshaped array to a 2-dimension array

In [7]:
# Example 2 - working
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

Suppose we give row as 1 and -1 as column then Numpy will able to find column as 8.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Old array has 8 elements totally, new array elements lenght doesn't match with old array lenght.To fix it, make sure you have matching elements in reshaped array.

In summary, when reshape array, the new shape must contain the same number of elements as the old shape, meaning the products of the two shapes’ dimensions must be equal. 

In [11]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations-assigment-2" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2


'https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2'

## Function 2 - setdiff1d
Use to find unique values in an array compared to another

In [12]:
# Example 1 - working
a = np.array([1, 2, 3, 4, 5])
b = np.array([3,4,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 5])

In this case, [1,2,5] which presented in a are not presented in b

In [13]:
# Example 2 - working
c = np.array([1, 3, 2, 4, 4, 5])
d = np.array([3,7,9,7,8, 4])
np.setdiff1d(c,d,assume_unique=True)

array([1, 2, 5])

Adding attribute: assume_unique, if value True, the input arrays are both assumed to be unique, which can speed up the calculation. Default is False.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1, 3, 2, 4, 4, 5])
b = np.array([None,3,7,9,7,8, 4])
np.setdiff1d(c,d)

array([1, 2, 5])

Function doesn't compare None between array, to fix it, either add attribute assume_unique=true, or skip None by using b[1:].

 The function quit helpful when you want to return the sorted, unique values in one array that are not in another.

In [15]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations-assigment-2" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2


'https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2'

## Function 3 - np.intersect1d

The function is to get sorted 1-D array of common and unique between arrays.

In [16]:
# Example 1 - working
a = np.array([1,3,7,9,11])
b = np.array([1,3,8,11,2])
np.intersect1d(a,b)

array([ 1,  3, 11])

The function is to find the intersection of two arrays a and b with sorted order, in this case, 1,3,11 are both presented in a and b.

In [17]:
# Example 2 - working
a = np.array([[1,3,7,9,11],
              [9,3,13,26,2]])
b = np.array([1,8,11,2])
np.intersect1d(a,b)

array([ 1,  2, 11])

The function is to find the intersection of multi-dimentional arrays as well,in this case, 1,2,11 are both presented in a and b.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1,3,7,9,11])
b = np.array([1,3,8,11,2])

n=np.intersect1d(a,b)
n

array([ 1,  3, 11])

The funtion does not take N arrays, it only compares 2. To intersect more than two arrays, use functools.reduce.

The function is quite useful when retrieving common and unique values between arrays. By default, function attributes assume_unique and return_indices are False.

In [20]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations-assigment-2" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2


'https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2'

## Function 4 - np.where

Use to return the indices of elements in an input array where the given condition is satisfied.

In [21]:
# Example 1 - working
a = np.array([11, 12, 13, 14, 15, 16, 17, 18])
np.where((a > 15))

(array([5, 6, 7]),)

To find the indexes of elements in this array that satisfy our given condition i.e. element should be greater than 15.

In [22]:
# Example 2 - working
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(a < 4 )

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

np.where not only support 1-dimension array, it's also support multi dimension arrays.

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[None, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(a < 4)

TypeError: '<' not supported between instances of 'NoneType' and 'int'

When condition is given, None can't be compared to 4, to fix it, either replace the None to '0', or skip it in index.

The funtion is very useful when you want to indice of elements in given array/arrays when condition is matched.

In [34]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nikgopale4/numpy-array-operations-assigment-2" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2


'https://jovian.ai/nikgopale4/numpy-array-operations-assigment-2'

## Function 5 - np.argmax/np.argmin

The function is to return the index position of the largest/smallest value from given 1-dimentional or multi-dimentional array

In [35]:
# Example 1 - working
a = np.array([0, 5, 2, 3, 4, 5])
print(np.argmax(a))
print(np.argmin(a))

1
0


The function returns the index of given 1-D array for maximum/minimum value.

In [36]:
# Example 2 - working
a = np.array([[0, 5, 2, 3, 4, 5],
             [6, 7, 8, 9, 90, 22]])
print(np.argmax(a))
print(np.argmin(a))

10
0


The function returns the index of given multi-dimential array for maximum/minimum value.

In [37]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([])
print(np.argmax(a))
print(np.argmin(a))

ValueError: attempt to get argmax of an empty sequence

Error happens when If the array is empty,  because ruth value of an array with more than one element is ambiguous, use a.any() or a.all() can fix the issue.

The function np.argmax/argmin is quite useful when getting the largest/smallest value from given array.

In [ ]:
jovian.commit(project='numpy-array-operations-assigment-2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

NumPy has many features to help build multi-dimensional arrays and perform calculations on the data stored in them. It's one of most popular libraries in machine learning and can make your life much eaier if you are working on data science.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* NumPy Creating Arrays : https://www.w3schools.com/python/numpy_creating_arrays.asp
* Operating on Numpy arrays : https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Operating_on_Numpy_Arrays.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
